### ISSUE TITLE
Rephrase task 3) in 3.3.2

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/Tutorials#111]
It uses our terminology of "elements" which is confusing.
Maybe give a hint, too.

**Comment by oliveralka** [comment]
Where does this apply? Please give the title of the chapter.

**Comment by jpfeuffer** [comment]
Metabolomics -> Visualize data -> Task 3)
Yeah the numbers changed. e.g. now 5.3.2 in the full handout.

**Comment by oliveralka** [comment]
@mrurik what did you wanted to say here? 
`Try to compute and visualize the m/z and retention time error of the different elements of the consensus features.`

**Comment by jpfeuffer** [comment]
Last time we agreed that we probably?? mean that you take all the different "consensus elements" (e.g features from the different maps) and calculate some statistics on them. E.g. Deviation from mean RT, deviation from consensus RT, etc. That should be done for every row. Can be done easily with a Math or the new Multi Math node.

**Comment by mrurik** [comment]
I did not write that specific task, but I would understand it in the same way as @jpfeuffer, i.e. we are interested in the deviation of the individual RTs from the mean RT. We should add that explanation and maybe hint towards the Multi Math node, otherwise this task is too difficult for new users.
