### ISSUE TITLE
Update msConvert image

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/Tutorials#130]
New drop down

**Comment by timosachsenberg** [comment]
please add to Boston 2018 branch

**Comment by Leon-Bichmann** [comment]
Ill do it this week. Didnt have access to my windows machine with MSConvert last week.

**Comment by Leon-Bichmann** [comment]
yes I thought so

**Comment by timosachsenberg** [comment]
can you check?

**Comment by Leon-Bichmann** [comment]
yep its merged
