### ISSUE TITLE
Loading MSStats missing

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/Tutorials#132]
the library(MSstats) call is missing in the tutorial.

**Comment by jpfeuffer** [comment]
also data <- knime.in is missing

**Comment by jpfeuffer** [comment]
also code for plotting the volcano plot is missing.

**Comment by timosachsenberg** [comment]
to be added to Boston 2018 branch

**Comment by timosachsenberg** [comment]
any update?
