### ISSUE TITLE
Metabo KNIME workflow picture is outdated

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/Tutorials#133]
And therefore wrong. MzTabexporter has only two outputs there.
People were confused.

**Comment by timosachsenberg** [comment]
to be added to Boston 2018 branch

**Comment by jpfeuffer** [comment]
any updates?

**Comment by mrurik** [comment]
I cannot find issues with MzTabExporter, does this refer to MzTabReader in Fig. 33?

**Comment by jpfeuffer** [comment]
Ah yes Reader.

**Comment by jpfeuffer** [comment]
I think everything should be solved if the pictures get updated. Coordinate with @oliveralka please

**Comment by oliveralka** [comment]
@mrurik As mentioned on Tuesday, it would be great if you could update the Figures 30, 32, 33, 37  as soon as possible.

**Comment by mrurik** [comment]
I updated Figures 30, 32, and 33. Not sure what needs to be updated in Figure 37.

**Comment by timosachsenberg** [comment]
to late for current tutorial but we might update that for the other ones
