### ISSUE TITLE
File missing in example data

### ISSUE THREAD

**Issue by jylanwhu** [OpenMS/Tutorials#167]
I would like to try the Metabolite_ID.knime workflow, but one file specified in the tutorial is missing.
The file name is: "Metabolite_ID_SpectraDB_positive.mzML"  Could you please send me or upload this file? Thanks!

**Comment by jpfeuffer** [comment]
Hi! Thanks for reporting.
The file is here: https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Tutorials/Data/latest/Example_Data/Metabolomics/datasets/

Which Handout.pdf did you use? Maybe we need to update the links/folder structures?

**Comment by jylanwhu** [comment]
Thanks! Please check https://www.openms.de/tutorials/, I downloaded the example data(850MB). The file was not in the package there.

**Comment by oliveralka** [comment]
Thanks for pointing that out!

@jpfeuffer Maybe we could link the abibuilder resource instead of having an additional package for the website.
