### ISSUE TITLE
exporting results of identification and quantitation as a table

### ISSUE THREAD

**Issue by pavel-shliaha** [OpenMS/Tutorials#177]
I have ran the identification and LFQ pipeline with identity propagation between runs and now I want to export the results of:

1. database search within the search loop, so I get a separate csv for every file including the AUC MS1 quantitation
2. peptide quantitation across files, including the source of each ID: database search or identity transfer

I am trying to use the TextExporter tool which I am connecting in the first case to IDMapper and in the second case to ConsensusMapNormaliser. However the results that are produced are in a very strange format (not one peptide per line I expected). Is this a bug, or is there a setting I am missing to create a useful csv?

**Comment by jpfeuffer** [comment]
Hi,

yes this is expected, it is a format with sections. In the beginning, you see the header lines of the different sections,
and then the sections start with a section identifier in the first column of each row.
You can use the FeatureTextReader (or similar) nodes to automatically parse this format and read it into KNIME again.
Then you can export it as a CSV.
