### ISSUE TITLE
Some of the OpenMS FileConverter requirements might be missing.

### ISSUE THREAD

**Issue by soerendip** [OpenMS/Tutorials#181]
I am trying to run the Turorials with a fresh KNIME installation 4.2.1. I installed the OpenMS nodes easily. Though the first time I ran the tutorial metabolite_ID, I got this message mentioned in the title. Then I followed the link and downloaded the OpenMS-2.5-prerequisites installer. But that did not solve the problem. I am running Windows10. Then I installed Proteowizzard, but I am not sure if that program actually works on Windows 10 as it is not showing up in the start menu. I reinstalled OpenMS 2.5 as well. I am also not sure what to try next. 

It would be amazing to also have a detailed description on how to install OpenMS with KNIME as part of the tutorials.

**Comment by oliveralka** [comment]
Hi @soerendip, 

have you had a look at the Tutorial handout:
https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Tutorials/Handout/release/2.6.0/handout.pdf

Chapter 2 - Getting started
should give you at least an idea on how to proceed with the installation. 

Please let us know how we could improve the chapter! 

The specific error "OpenMS FileConverter requirements might be missing", seems to be an issue on our side with the windows registry - we will take a look! If everything else runs the error can be savely ignored currently.

**Comment by soerendip** [comment]
The first two nodes of the Metabolite_ID workflow run well, but the FeatureFinderMetabo - actually what is the difference between that and FeatureFindingMetabo?- has a yellow sign with an exclamation mark. Ok, I just found the error. I was using mzXML files instead of mzML files. The Load node succeeded regardless. The console showed the error message that a different file ending is expected. ...bloody new to OpenMS with KNIME. Cheers!
