### ISSUE TITLE
Placement of code examples via minted 

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/Tutorials#194]
We have to check if the code examples (minted environment) have the correct placement. 
It seems that they float and are not in the places in the text, where they should be. 

Any suggestions?

Example 1:
![Screenshot 2021-07-19 at 19 36 59](https://user-images.githubusercontent.com/15729190/126202674-48841a24-c85a-4c13-b7ec-9670dcaf99d1.png)
Example 2:
![Screenshot 2021-07-19 at 19 36 09](https://user-images.githubusercontent.com/15729190/126202682-a05072c4-0d3a-41d7-97eb-608587b5481b.png)

**Comment by jpfeuffer** [comment]
I guess something like putting it inside a non-floating environment instead might work:
https://tex.stackexchange.com/questions/254044/caption-and-label-on-minted-code/254177
https://tex.stackexchange.com/questions/12428/code-spanning-over-two-pages-with-minted-inside-listing-with-caption/53540
