### ISSUE TITLE
Java version check possibly errornous

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/Tutorials#27]
ERROR MSGFPlusAdapter      0:7        Failing process stderr: [Error: Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion', has value '1.8', but '1.7' is required., Error: could not find java.dll, Error: Could not find Java SE Runtime Environment.

**Comment by jpfeuffer** [comment]
Is this still an issue?
