### ISSUE TITLE
Bonus task: id using several search engines not working with xtandem 10ppm

### ISSUE THREAD

**Issue by FabianAicheler** [OpenMS/Tutorials#35]
.. "set its parameters and ports analogously to the OMSSAAdapter". Fixed and variable modifications works fine, however if precursor_mass_tolerance of XTandemAdapter is changed to 10ppm (from default value 1.5 ppm !), this error results with lfq_spikein_dillution_3.mzML:

ERROR PeptideIndexer       0:7        Failing process stdout: [Mapping 2287 peptides to 7614 proteins., Aho-Corasick done. Found 4256 hits in 2285 of 2287 peptides (time: 0.436414 s (wall), 0.4375 s (CPU))., Using suffix array to find ambiguous matches..., ... for 2 peptide(s)., Peptide hits passing enzyme filter: 4256,      ... rejected by enzyme filter: 8, Unmatched peptide: PSLSTQGLDPSLSEQGPD, Statistics of peptides (target/decoy):, <Unmatched peptide: PSLSTQGLDPSLSEQGPD> occurred 2 times,   match to target DB only: 2046,   match to decoy DB only : 239,   match to both          : 0, Statistics of peptides (mapping to proteins):,   no match (to 0 protein)         : 2,   unique match (to 1 protein)     : 337,   non-unique match (to >1 protein): 1948, PeptideIndexer found unmatched peptides, which could not be associated to a protein., Potential solutions:,    - check your FASTA database for completeness,    - set 'enzyme:specificity' to match the identification parameters of the search engine,    - some engines (e.g. X! Tandem) employ loose cutting rules generating non-tryptic peptides;,      if you trust them, disable enzyme specificity,    - increase 'aaa_max' to allow more ambiguous amino acids,    - as a last resort: use the 'allow_unmatched' option to accept unmatched peptides,      (note that unmatched peptides cannot be used for FDR calculation or quantification), Result files were written, but PeptideIndexer will exit with error code., Statistics of proteins:,   new proteins: 1226,   orphaned proteins: 0 (all removed), PeptideIndexer took 0.90 s (wall), 0.91 s (CPU), 0.05 s (system), 0.86 s (user).]
ERROR PeptideIndexer       0:7        Failing process stderr: []
ERROR PeptideIndexer       0:7        Execute failed: Failed to execute node PeptideIndexer

Setting Enzyme specicity to "semi" in PeptideIndexer does not help ("none" helps)

Workflow is attached (just in case i overlooked some params etc)
[labelfree_consensus.zip](https://github.com/OpenMS/Tutorials/files/299023/labelfree_consensus.zip)

**Comment by jpfeuffer** [comment]
Hmm I think the error message describes it very well. I guess it was just overlooked while testing the workflow. If you still get the nice boxplots in the end, we should update the settings in the tutorial.
I.e. say that XTandem has this weird behaviour and to use specificity=none in the indexer.
Long version would be to look for settings in XTandem that force it to behave like everyone would expect and not make exceptions on its own.

**Comment by timosachsenberg** [comment]
should be fixed with Fabians PR https://github.com/OpenMS/Tutorials/pull/36

**Comment by FabianAicheler** [comment]
Didn't really check whether the box plots look nice, as XtandemAdapter is only used in the consensensus example (where no data analysis occurs).

Best,
Fabian

----- Original Message -----

**Comment by FabianAicheler** [comment]
Would say can be closed.

**Comment by jpfeuffer** [comment]
Agree.
