### ISSUE TITLE
QC workflow; update mit community-contributions/trunke/ zereisst workflow

### ISSUE THREAD

**Issue by FabianAicheler** [OpenMS/Tutorials#37]
Das nötige update (http://tech.knime.org/update/community-contributions/trunk/) scheint zu einem falsch gesetzten OPENMS_DATA_PATH zu führen. Grade gesehen dass das KNIME lokal zu sein scheint/der Path spontan immer gesetzt wird? Auf jeden Fall kann man deshalb nichtmal mit eigenem OPENMS_DATA_PATH fixen!!!

ERROR OMSSAAdapter         0:18       Failing process stderr: [OpenMS FATAL ERROR!,   Cannot find shared data! OpenMS cannot function without it!,   The environment variable 'OPENMS_DATA_PATH' currently points to 'C:/dev/KNIME_PACKAGE/trunk/OpenMS/share/OpenMS', which is incorrect!,   To resolve this, set the environment variable 'OPENMS_DATA_PATH' to the OpenMS share directory (e.g., 'c:\Program Files\OpenMS\share\OpenMS')., Exiting now.]

**Comment by FabianAicheler** [comment]
Tested on KNIME 3.1.2

**Comment by mwalzer** [comment]
How does this relate to QC in particular?
This seems to be an issue of either OMSSA or how KNIME is handling it.
If ID is working with any other Workflow, then replace the corresponding nodes.

**Comment by FabianAicheler** [comment]
Because the necessary update is only mentioned in the QC section. And it affects more nodes than OMSSA (at least also the FeatureFinderCentroid in the workflow, thus I assume all tool nodes)

So, without the update no QCCreator if I saw correctly, with update OpenMS tool nodes don't work anymore

**Comment by jpfeuffer** [comment]
I had this problem recently together with Sandro.
Are you on Mac or Windows?

**Comment by jpfeuffer** [comment]
Yes, the path is internally set by the JavaVM of KNIME and can be found in the binaries.ini.
https://github.com/OpenMS/OpenMS/blob/develop/cmake/knime/binaries_mac.ini
You can modify it under your KNIME.app/Contents/Eclipse/plugin/de.openms.platform.arch.version/payload/bin folder.

Maybe those inis got mixed up on the build machines??

**Comment by jpfeuffer** [comment]
The files on the KNIME trunk plugin site look fine on the first glance.

**Comment by FabianAicheler** [comment]
i used windows

**Comment by mwalzer** [comment]
Um, have you tried it _without_ the update? It was mentioned in the tutorial, because some tool updates haven't been in the knime build.
@jpfeuffer in which version is the knime build used for the tutorial?

**Comment by jpfeuffer** [comment]
We should use 2.0.

**Comment by mwalzer** [comment]
And which version is the knime build you get using the tutorial? 2.0.1 or 2.0.0?

**Comment by jpfeuffer** [comment]
We advise to use the latest stable plugin or the full installer of KNIME, both including OpenMS2.0.0 nodes.

**Comment by jpfeuffer** [comment]
But trunk is of course 2.0.1 because it follows develop. Although a solution would be to never use the trunk nodes, this needs to be solved.

**Comment by FabianAicheler** [comment]
without the develop update, there is e.g., no QCCreator node available.

latest stable (i.e. full installation followed by update) is 
  OpenMS	2.0.0.201605271126

**Comment by jpfeuffer** [comment]
Yes, the current date only comes from some IO nodes that I added.

**Comment by jpfeuffer** [comment]
Hmm okay.. the openms_data_path.h.in is not correctly configured on our build machine for the trunk build. It has Unix paths????!111

**Comment by jpfeuffer** [comment]
I cant see where it goes wrong. On our build machines, the openms_data_path.h configured by CMake looks fine (it has Windows paths). Also the binaries_win.ini uploaded to KNIME looks fine. I am out of ideas.

**Comment by mwalzer** [comment]
I also dont get it - in my fresh installation of knime3 and the http://tech.knime.org/update/community-contributions/${YOUR_KNIME_VERSION}/OpenMS, there is: de.openms.linux.x86_64_2.0.0.201605271126/QCCalculator

**Comment by FabianAicheler** [comment]
Do you mean QCCreator?

**Comment by FabianAicheler** [comment]
Hi, what's the current status on the problem?

Was the problem with the openms_data_path.h.in fixed/did that solve it? If yes, could someone verify the tutorial section?


Otherwise, my understanding is that the whole QC section can not be used in its current form.

Best,
Fabian


----- Original Message -----

**Comment by mwalzer** [comment]
@FabianAicheler replace QCCreator with QCCalculator and it should be fine. Where is QCCreator mentioned in the tutorial?

**Comment by FabianAicheler** [comment]
@mwalzer 8.2 Building a qcML file per run -> Initial paragraph,and following construction steps of the workflow.

**Comment by FabianAicheler** [comment]
Ok, currently testing section with QCcalculator instead of QCCreator.

**Comment by FabianAicheler** [comment]
Seems like the tut section works fine when using the QCCalculator. Tested with Knime 3.1.2 full install,     OpenMS	2.0.0.201605271126, no bleeding edge required.

Respective pull request by me should solve the issue at least for the Tutorial.
