### ISSUE TITLE
DAG shift key icon not easily recognized (up key???)

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/Tutorials#61]

**Comment by timosachsenberg** [comment]
fixed in BOSTON2017

**Comment by jpfeuffer** [comment]
I think with wider keys it will be recognized much better.
But I agree that we should either add a name in the key or in parentheses after the key.
I think this is mostly sufficiently addressed in BOSTON 2017, yes. We will merge this to master after the tutorial.
