### ISSUE TITLE
TOPP and TOPPView tutorial seem to not be typeset correctly

### ISSUE THREAD

**Issue by gPirkes** [OpenMS/Tutorials#68]
The TOPP_tutorial which is downloadable from https://www.openms.de/tutorials/ seems to not be typeset correctly, starting from page 22. Some of the text is extending off the page and therefore not readable, and some of the pictures are just referenced, but not shown.

**Comment by jpfeuffer** [comment]
Thanks a lot. I fixed that some weeks ago. I forgot to rebuild and reupload. I will do so now.
