### ISSUE TITLE
Remove second FASTA DB 

### ISSUE THREAD

**Issue by jpfeuffer** [OpenMS/Tutorials#76]
In the peptide Id and lfq part. Only confuses people. Is this used anywhere?  I mean the s_pyogenes.. And the uniprot _.. Ones

**Comment by timosachsenberg** [comment]
good idea. 
Also, I would suggest we use comet if possible and change REV_ to DECOY_ so it works out of the box with the default settings in PeptideINdexer

**Comment by timosachsenberg** [comment]
done for the data in GCB2017

**Comment by timosachsenberg** [comment]
also changed REV_ to DECOY_ and recreated psq files

**Comment by jpfeuffer** [comment]
Did you change that in all the nodes (e.g. PeptideIndexer), too?

**Comment by timosachsenberg** [comment]
no not yet in the wfs
