### ISSUE TITLE
Add MS2 example

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/Tutorials#86]
![isolation_ms2](https://user-images.githubusercontent.com/5803621/31342677-d179eb0c-ad0d-11e7-8a3d-b6e58cf4a6d4.png)

**Comment by timosachsenberg** [comment]
not sure if an explanation like this would help in the tutorial as it looks different in TOPPView.
Opinions?

**Comment by oliveralka** [comment]
I think it would help - needs to be added to p.12 - Data visualisation in TOPPView
