### ISSUE TITLE
Working with chemical structures

### ISSUE THREAD

**Issue by mrurik** [OpenMS/Tutorials#87]
How do you work with molecular structures, what is SMILES, how do you visualize structures and how can you filter them.
Example: 100 structures as SMILES -> in KNIME table -> filter by substructure. Demonstrate added value of KNIME/OpenMS workflows for working with spectra and structures.
Show this also in conjunction with metabolite identification.

**Comment by oliveralka** [comment]
Add below "minimal openms workflow" 
2.4.8 Workflow for visualization of chemical structures
