### ISSUE TITLE
Add profile vs centroid spectra 

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/Tutorials#88]
add picture profile vs centroid spectra 
page9 - MSConvertGUI

**Comment by timosachsenberg** [comment]
![bildschirmfoto 2017-10-10 um 19 28 12](https://user-images.githubusercontent.com/5803621/31401064-ef52b688-adf1-11e7-882f-f61d11b8061c.png)

**Comment by timosachsenberg** [comment]
I'll add another image

**Comment by timosachsenberg** [comment]
will push it to github

**Comment by timosachsenberg** [comment]
added it
