### ISSUE TITLE
Add picture 3D view 

### ISSUE THREAD

**Issue by oliveralka** [OpenMS/Tutorials#90]
Add picture of 3D View in ToppView Tutorial
page 11

**Comment by timosachsenberg** [comment]
![3dview](https://user-images.githubusercontent.com/5803621/31400757-0a4cf030-adf1-11e7-80d0-b06d539b6aec.png)

**Comment by hroest** [comment]
:+1:

**Comment by timosachsenberg** [comment]
pushed png to repo
